/* eslint-disable */
export const SETGAME = 'set-game'
export const UPDATEBOARD = 'update-board'
export const UPDATEPIECES = 'update-pieces'
export const ADDPIECES = 'add-pieces'
export const SELECTSQUARE = 'select-square'
export const DESELECTSQUARE = 'deselect-square'
export const UPDATEBATTLELOGS = 'update-battle-logs'
export const UPDATEMOVES = 'update-move-logs'
export const SETPENDINGMOVE = 'set-pending-move'
export const CANCELPENDINGMOVE = 'cancel-pending-move'
export const SETPLAYERTOKENS = 'set-player-tokens'
export const SETPLAYERPIECE = 'set-player-piece'
export const SETPLAYERADJACENTSQUARES = 'set-player-adjacent-squares'
export const SELECTDOOMIE = 'select-doomie'
