/* eslint-disable */
export const JOIN = 'join'
export const ABOUT = 'about'
export const SETTINGS = 'settings'
export const BUYNFT = 'buy-nft'
export const JOINGAME = 'join-game'
export const ENDTURN = 'end-turn'
export const RESET = 'reset'
export const LOGGEDIN = 'logged-in'
export const INGAME = 'in-game'
export const SQUARESTATE = 'square-state'
export const BATTLEFINISHED = 'battle-finished'
export const CLOSE = 'close'
export const PLAYER = 'player'
export const WEAPON = 'weapon'
export const MAXTOKENS = 800
export const S3_SUFFIX: string = 'https://doomies-img-public.s3.us-east-2.amazonaws.com/doomies/'
